### ISSUE TITLE
Ngrok not working i am greeted with a sign in page

### ISSUE THREAD

**Issue by CrayZscotsman** [ultrasecurity/Storm-Breaker#89]
link sends me to a sign up page and auth token system

**Comment by KrishnaSharma000** [comment]
+1

**Comment by zMatix** [comment]
+1

**Comment by WolfDev65** [comment]
+1

**Comment by JustinH71** [comment]
Create an account at Ngrok.com. Once you've created your account click on getting started on the left side of the screen.
You'll see a link called Your Authtoken. Click on that link and use the token on top with only letter and numbers. Open up 
StormBreaker. Cd into Storm-Breaker
─$ cd Storm-Breaker. Get root access by typing sudo su. Once you have root type ngrok and paste your token number and hit enter.
It should tell you that your token was saved. Then run Storm-Breaker. 
 Don't use ./ngrok authtoken 22342322..ect

**Comment by mari1179** [comment]
it dose not work for me

**Comment by mari1179** [comment]
┌──(root💀kali)-[/home/kali/Strome-breaker]
└─# ngrok  22xmpoa2oEDw61Mg4Mp1yNm3GBc_HZ6RSUAhnmbszg4wUAN4 
NAME:
   ngrok - tunnel local ports to public URLs and inspect traffic

DESCRIPTION:
    ngrok exposes local networked services behinds NATs and firewalls to the
    public internet over a secure tunnel. Share local websites, build/test
    webhook consumers and self-host personal services.
    Detailed help for each command is available with 'ngrok help <command>'.
    Open http://localhost:4040 for ngrok's web interface to inspect traffic.

EXAMPLES:
    ngrok http 80                    # secure public URL for port 80 web server
    ngrok http -subdomain=baz 8080   # port 8080 available at baz.ngrok.io
    ngrok http foo.dev:80            # tunnel to host:port instead of localhost
    ngrok http https://localhost     # expose a local https server
    ngrok tcp 22                     # tunnel arbitrary TCP traffic to port 22
    ngrok tls -hostname=foo.com 443  # TLS traffic for foo.com to port 443
    ngrok start foo bar baz          # start tunnels from the configuration file

VERSION:
   2.3.40

AUTHOR:
  inconshreveable - <alan@ngrok.com>

COMMANDS:
   authtoken    save authtoken to configuration file
   credits      prints author and licensing information
   http         start an HTTP tunnel
   start        start tunnels by name from the configuration file
   tcp          start a TCP tunnel
   tls          start a TLS tunnel
   update       update ngrok to the latest version
   version      print the version string
   help         Shows a list of commands or help for one command

ERROR:  Unrecognized command: 22xmpoa2oEDw61Mg4Mp1yNm3GBc_HZ6RSUAhnmbszg4wUAN4






its coming like this 
what can i do for it

**Comment by JustinH71** [comment]
When you run storm-breaker it will give you list of options. One of those options is settings. I think it's number 5. If not press the number that has settings and paste just the token number like this: 22xmpoa2oEDw61Mg4Mp1yNm3GBc_HZ6RSUAhnmbszg4wUAN4  . See if that works. 
    On Wednesday, December 29, 2021, 07:35:18 AM MST, mari1179 ***@***.***> wrote:  
 
 


┌──(root 💀 kali)-[/home/kali/Strome-breaker]
└─# ngrok 22xmpoa2oEDw61Mg4Mp1yNm3GBc_HZ6RSUAhnmbszg4wUAN4
NAME:
ngrok - tunnel local ports to public URLs and inspect traffic

DESCRIPTION:
ngrok exposes local networked services behinds NATs and firewalls to the
public internet over a secure tunnel. Share local websites, build/test
webhook consumers and self-host personal services.
Detailed help for each command is available with 'ngrok help '.
Open http://localhost:4040 for ngrok's web interface to inspect traffic.

EXAMPLES:
ngrok http 80 # secure public URL for port 80 web server
ngrok http -subdomain=baz 8080 # port 8080 available at baz.ngrok.io
ngrok http foo.dev:80 # tunnel to host:port instead of localhost
ngrok http https://localhost # expose a local https server
ngrok tcp 22 # tunnel arbitrary TCP traffic to port 22
ngrok tls -hostname=foo.com 443 # TLS traffic for foo.com to port 443
ngrok start foo bar baz # start tunnels from the configuration file

VERSION:
2.3.40

AUTHOR:
inconshreveable - ***@***.***

COMMANDS:
authtoken save authtoken to configuration file
credits prints author and licensing information
http start an HTTP tunnel
start start tunnels by name from the configuration file
tcp start a TCP tunnel
tls start a TLS tunnel
update update ngrok to the latest version
version print the version string
help Shows a list of commands or help for one command

ERROR: Unrecognized command: 22xmpoa2oEDw61Mg4Mp1yNm3GBc_HZ6RSUAhnmbszg4wUAN4

its coming like this
what can i do for it

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
